version: '3'
services:
  app:
    build:
      dockerfile: ./spring.dockerfile
      context: .
    container_name: spring
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    networks:
      - projeto-network
  database:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nativa
      PGDATA: /data/postgres
    ports:
      - "5434:5432"
    networks:
      - projeto-network
    restart: unless-stopped

networks:
  projeto-network:
    driver: bridge
